{{- if eq (.Values.kind  | lower) "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    helm.sh/chart: {{ template "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      priorityClassName: {{ .Values.pod.priorityClassName }}
      {{- if .Values.pod.affinity }}
      affinity:
{{ toYaml .Values.pod.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.pod.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.pod.nodeSelector | indent 8 }}
      {{- end }}
      tolerations:
{{ include "tolerations" . | indent 8 }}
      {{- if .Values.pod.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      hostNetwork: true
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.keepalived.debug }}
        args: ["debug"]
        {{- end }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
{{ include "environmentvars" . | indent 10 }}
        {{- if .Values.pod.resources }}
        resources:
{{ toYaml .Values.pod.resources | indent 10 }}
        {{- end }}
{{- end }}