{{- if eq (.Values.kind  | lower) "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    helm.sh/chart: {{ template "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pod.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      priorityClassName: {{ .Values.pod.priorityClassName }}
      affinity:
        # Do not co-locate multiple keepalived pods on a single node.
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ template "app.name" . }}
            topologyKey: "kubernetes.io/hostname"
      {{- if .Values.pod.affinity }}
{{ toYaml .Values.pod.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.pod.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.pod.nodeSelector | indent 8 }}
      {{- end }}
      tolerations:
{{ include "tolerations" . | indent 8 }}
      {{- if .Values.pod.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      hostNetwork: true
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.keepalived.debug }}
        args: [ "/usr/sbin/keepalived", "-l", "-n", "-f", "/etc/keepalived/keepalived.conf", "-D" ]
        {{- end }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
{{ include "environmentvars" . | indent 10 }}
        {{- if .Values.pod.resources }}
        resources:
{{ toYaml .Values.pod.resources | indent 10 }}
        {{- end }}
{{- end }}